version: "3"

services:
  nginx:
    build: ./requirements/nginx
    container_name: "nginx"
    ports:
      -  "443:443"
    volumes:
      - wp_vol:/var/www/html
    networks:
      - inception
#    restart: on_failure

  wordpress:
    build: ./requirements/wordpress
    container_name: "wordpress"
    ports:
      - "127.0.0.1:9000:9000"
    volumes:
      - wp_vol:/var/www/html
    networks:
      - inception
#    restart: on_failure


networks:
  inception:

volumes:
  wp_vol:
    driver: local
    driver_opts:
      type: none
      device: /home/clbouche/data/wp_vol
      o: bind